[package]
name = "transpo-rt"
version = "0.1.0"
authors = ["antoine-de <antoine.desbordes@gmail.com>", "Tristram Gräbener <tristramg@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
env_logger = "0.6"
futures = "0.1"
reqwest = "0.9"
log = "0.4"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1"
bytes = "0.4"
prost = "0.4"
prost-derive = "0.4"
serde = "1.0"
serde_derive = "1"
structopt = "0.2"
navitia_model = { git = "https://github.com/CanalTP/navitia_model.git", rev = "724b1b3d77ce9871cb02ff87c2d78fe64b2b27c0" }
chrono-tz = "0.5"
serde_yaml = "0.8"

[dev-dependencies]
serde_json = "1.0"
mockito = "0.14"

[build-dependencies]
prost-build = "0.4"

