[package]
name = "transpo-rt"
version = "0.1.0"
authors = ["antoine-de <antoine.desbordes@gmail.com>", "Tristram Gräbener <tristramg@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.7"
actix-web = "0.7"
env_logger = "0.6"
reqwest = "0.9"
log = "0.4"
chrono = "0.4"
failure = "0.1"
bytes = "0.4"
prost = "0.4"
prost-derive = "0.4"
serde = "1.0"
serde_derive = "1"
gtfs-structures = "0.8"
structopt = "0.2"
navitia_model = { git = "https://github.com/antoine-de/navitia_model.git", rev = "e02b0ec1e3232b5245245698d7448d1709ae0a4b" }

[dev-dependencies]
serde_json = "1.0"

[build-dependencies]
prost-build = "0.4"
