version: 2

defaults: &defaults
  docker:
    - image: circleci/rust:latest

jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          command: cargo test -j3
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

  linter:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: lint-cache
      - run:
          command: "rustup component add rustfmt-preview clippy-preview"
      - run:
          command: "cargo fmt --all -- --check"
      - run:
          command: "cargo clippy -- -D warnings"
      - save_cache:
          key: lint-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  version: 2
  build_and_test:
    jobs:
      - tests
      - linter
